### ISSUE TITLE
Due to changes on Vidstreaming.io, m3u8 is currently unusable

### ISSUE THREAD

**Issue by ShujianDou** [vrienstudios/vidstreamdownloader#13]
It has been fixed for C#, for JS version, it will only download mp4.

**Comment by qinatsu** [comment]
Sad

**Comment by ShujianDou** [comment]
Should be fixed later today

**Comment by ShujianDou** [comment]
Fixed in recent commit

**Comment by qinatsu** [comment]
mp4 works

**Comment by qinatsu** [comment]
I initially added m3u8 support to JS version as some shows were only available for m3u8 format, but now that they are all available on mp4 format I don't see any reason to bring m3u8 back, but if somebody else re-implements it I'll be glad to accept it

**Comment by qinatsu** [comment]
And still gonna keep the m3u8 download in the video module just in case
